### PR TITLE
cmd/{apigen,subcmd/doc}.go: if err != nil { fail(err) } -> check(err)

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by elimisteve** [comment]
Handy! https://golang.org/pkg/log/#Fatal

**Comment by konradreiche** [comment]
I have a preference to keep it as is. I have code where I do provide a helper function but it usually performs a few more actions. I think for educational purposes it is good to present the reader with the common paradigm we are used to in Go.

**Comment by elimisteve** [comment]
If that's the goal then I suggest that you use https://golang.org/pkg/log/#Fatal instead of creating your own nearly-identical `fail` function.

**Comment by konradreiche** [comment]
Totally agree

**Pull request closed without merging**
